const imageBasePath = "/images";
const homeBasePath = `${imageBasePath}/home`;
const itineraryBasePath = `${imageBasePath}/itinerary`;

export const images: ImageDictionary = {
  home: {
    itineraryTab: `${homeBasePath}/tab1.png`,
    preparationTab: `${homeBasePath}/tab2.jpg`,
    frenzyTab: `${homeBasePath}/tab3.jpg`,
    expenditureTab: `${homeBasePath}/tab4.webp`,
    verticalBanner: `${homeBasePath}/verticalBanner.jpg`,
    horizontalLeft: `${homeBasePath}/horizontalLeft.jpg`,
    horizontalRight: `${homeBasePath}/horizontalRight.png`,
  },
  itinerary: {
    placeholder: `${imageBasePath}/placeholder.png`,
    tripDotCom: `${itineraryBasePath}/tripDotCom.png`,
    ameyoko: `${itineraryBasePath}/ameyoko.jpg`,
    animateIkebukuro: `${itineraryBasePath}/animateIkebukuro.jpg`,
    asakusaBattingStadium: `${itineraryBasePath}/asakusaBattingStadium.jpg`,
    atHomeCafe: `${itineraryBasePath}/atHomeCafe.jpg`,
    changiAirport: `${itineraryBasePath}/changiAirport.jpg`,
    changiAirportLounge: `${itineraryBasePath}/changiAirportLounge.jpeg`,
    dawnAvatarRobotCafe: `${itineraryBasePath}/dawnAvatarRobotCafe.jpg`,
    donQuijote: `${itineraryBasePath}/donQuijote.jpg`,
    genrokuzushi: `${itineraryBasePath}/genrokuzushi.webp`,
    grillCardinal: `${itineraryBasePath}/grillCardinal.jpg`,
    gyukatsuMotomura: `${itineraryBasePath}/gyukatsuMotomura.jpg`,
    haileyCafe: `${itineraryBasePath}/haileyCafe.jpg`,
    hoboShinjukuNorengai: `${itineraryBasePath}/hoboShinjukuNorengai.jpg`,
    katsuCurry: `${itineraryBasePath}/katsuCurry.jpg`,
    kotogase: `${itineraryBasePath}/kotogase.jpg`,
    mangaMuseum: `${itineraryBasePath}/kyotoMangaMuseum.jpg`,
    meguroRiver: `${itineraryBasePath}/meguroRiver.jpg`,
    meijiShrine: `${itineraryBasePath}/meijiShrine.jpg`,
    mishimaSkywalk: `${itineraryBasePath}/mishimaSkywalk.webp`,
    nadaiFujisoba: `${itineraryBasePath}/nadaiFujisoba.jpg`,
    naritaAirport: `${itineraryBasePath}/naritaAirport.jpg`,
    naritaExpress: `${itineraryBasePath}/naritaExpress.jpg`,
    osakaAquarium: `${itineraryBasePath}/osakaAquarium.jpg`,
    redTokyoTower: `${itineraryBasePath}/redTokyoTower.jpg`,
    scootTakeOff: `${itineraryBasePath}/scootTakeOff.jpg`,
    shibuyaSky: `${itineraryBasePath}/shibuyaSky.jpg`,
    shinjukuWashingtonHotel: `${itineraryBasePath}/shinjukuWashingtonHotel.webp`,
    sightseeingCruise: `${itineraryBasePath}/hakoneSightseeingCruise.jpg`,
    solaniwa: `${itineraryBasePath}/solaniwa.jpg`,
    soupNoodleRamen: `${itineraryBasePath}/soupNoodleRamen.jpg`,
    sunshineCity: `${itineraryBasePath}/sunshineCity.jpg`,
    takeshitaStreet: `${itineraryBasePath}/takeshitaStreet.jpg`,
    tokyoJoypolis: `${itineraryBasePath}/tokyoJoypolis.jpg`,
    tokyoRoastery: `${itineraryBasePath}/tokyoRoastery.jpg`,
    tokyoSkytree: `${itineraryBasePath}/tokyoSkytree.jpg`,
    tokyoUniversity: `${itineraryBasePath}/tokyoUniversity.jpg`,
    uenoPark: `${itineraryBasePath}/uenoPark.jpg`,
    yoyogiPark: `${itineraryBasePath}/yoyogiPark.jpg`,
  },
};

type ImageDictionary = {
  [type: string]: {
    [item: string]: string;
  };
};

export enum Image {
  placeholder = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/20230118224158.png?alt=media&token=14f0f867-0caf-4bce-909a-2ac2eb639a1a",
  animateIkebukuroMarinRoom = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/AnimateIkebukuroMarinRoom.jpg?alt=media&token=2b63bd62-6834-4548-a411-aff829472827",
  animateIkebukuroSelfieWithMarin = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/AnimateIkebukuroSelfieWithMarin.png?alt=media&token=3270e305-f90c-4f71-90a8-5d076c8f8452",
  animeJapanPeacePose = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/AnimeJapanPeace.jpg?alt=media&token=1f9e603e-bc46-4b2f-ab0f-57b9a2353516",
  animeJapanWithMiku = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/AnimeJapanWithMiku.jpg?alt=media&token=3cf321ef-8dd1-431d-8f3a-fe73e078f03f",
  animeJapanWithMikuAndBro = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/AnimeJapanMikuWithBro.jpg?alt=media&token=68e8dced-3cfc-4dd0-80fc-d27529de11fa",
  arashiyamaBambooGroveWithBro = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/ArashiyamaBambooWithBro.jpg?alt=media&token=6a0ac740-a944-4de3-9854-c1affc64835a",
  arrivalTemperature = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/ArrivalTemperature.jpg?alt=media&token=dde31888-4844-4e7b-ad88-075aed17dfab",
  atHomeCafeMain = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/AtHomeCafeMain.jpg?alt=media&token=9a23a8dd-0542-4d50-989d-4abbbbeb7ccd",
  atHomeCafeDrink = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/AtHomeCafeDrink.jpg?alt=media&token=87b27497-e7c5-43cd-acc6-2550c7bf36a7",
  atHomeCafeDessert = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/AtHomeCafeDessert.jpg?alt=media&token=61adf90c-a767-44f2-bb04-de3cacdb7a94",
  baggageIdTag = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/BaggageIdentificationTag.png?alt=media&token=1552c32d-f748-4c94-bc10-65b5d7956fcf",
  beefLasagne = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/BeefLasagne.jpg?alt=media&token=f80b9eb9-a7ff-48dd-be0e-6f8eb28357f3",
  boardingPass = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/BoardingPass.jpg?alt=media&token=3a848f8d-2e27-43e1-9077-c93cdac1a054",
  bunkaGakuenSakura = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/BunkaGakuenSakura.jpg?alt=media&token=758b7eba-31b3-4539-ad68-f31509e17afe",
  chilliCrabWithMantou = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/ChilliCrabMantou.jpg?alt=media&token=25e32103-46ba-4925-8e32-a37b922c1e57",
  dangoWithBro = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/DangoWithBro.jpg?alt=media&token=622a8aab-b83f-4f05-8341-a60e5381ca2a",
  dawnCafeWithGroup = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/DawnCafeWithGroup.jpg?alt=media&token=6202ebf0-fdf2-447e-bc97-e52e217cb134",
  dawnCafeWithMoon = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/DawnCafeWithMoon.jpg?alt=media&token=f28bc275-8f3f-4384-b1f8-55c606e79e37",
  donkiHachiko = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/DonkiHachiko.jpg?alt=media&token=118dfca9-8b41-4e16-acdf-bbcb172cb371",
  donkiTenYenWithDog = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/Donki10YenWithDog.jpg?alt=media&token=b72fb9c1-b99c-4165-85a4-e73a8c959022",
  fier = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/Fier.jpg?alt=media&token=bf9871c3-a06e-4781-841e-2618f2ad2039",
  fushimiInariWagyuSkewer = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/FushimiInariWagyuSkewer.jpg?alt=media&token=50da46f0-ec86-47d8-8c42-41f9f6af2766",
  gotembaBusWithBro = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/GotembaBusWithBro.jpg?alt=media&token=48efe838-c2c5-419e-9c25-e0952b869fbf",
  gotembaBusStopWithBro = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/GotembaBusStopWithBro.jpg?alt=media&token=18f52abc-0a7b-4a3f-be0e-eeab810ab971",
  gotembaCrepe = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/GotembaCrepe.jpg?alt=media&token=26cf8679-d8ff-4d7e-bea8-ba6a34273ad7",
  gotembaPikachu = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/GotembaPikachu.jpg?alt=media&token=e2b6696f-837a-48c3-a489-26a558e23a24",
  gyukatsuMotomuraMenu = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/GyukatsuMotomuraMenu.jpg?alt=media&token=623d3adc-440e-4734-9044-bb4757d4f14f",
  gyukatsuMotomuraMealWithBro = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/GyukatsuMotomuraMealWithBro.jpg?alt=media&token=9765477f-2cc8-484a-82d3-30b668e823cb",
  gyukatsuMotomuraSelfService = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/GyukatsuMotomuraSelfService.gif?alt=media&token=5fe8251e-81a5-4835-b0c7-b6ac00f8362e",
  gyukatsuMotomuraSetMeal = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/GyukatsuMotomuraSetMeal.jpg?alt=media&token=5911ee58-3474-4143-9ca5-28530222efd7",
  haileyCafeComputer = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/HaileyCafeComputer.jpg?alt=media&token=db128a82-88d5-4c3a-8a84-b3cbd94dc9d3",
  haileyCafeReadManga = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/HaileyCafeReadManga.jpg?alt=media&token=ec5a4153-6615-4d08-a3e9-a791830eb87f",
  hakoneToriiWithBro = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/HakoneToriiWithBro.jpg?alt=media&token=d21bce35-e654-4bd5-a0e2-66a5a34556db",
  iwatayamaTickets = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/IwatayamaTickets.jpg?alt=media&token=70160394-3e74-4fff-89c8-e7043fae7ad6",
  kotagaseCloseUpWithBro = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/KotagaseCloseUpWithBro.jpg?alt=media&token=4ce5a139-9302-4982-b3c0-de72b4191333",
  kotagaseWithBro = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/KotagaseWithBro.jpg?alt=media&token=684675dd-8a01-489c-be04-b346cbcefdc9",
  kotagaseWithPikachu = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/KotagaseWithPikachu.jpg?alt=media&token=b9555b03-0a2d-4b4a-8ff3-d03574c07fe7",
  kyotoMangaMuseumWithBro = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/KyotoMangaMuseumWithBro.jpg?alt=media&token=8416b352-1631-498a-8c16-a90d00b27608",
  loungeCoffeeMaking = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/LoungeCoffeeMaking.jpg?alt=media&token=946b8727-ff92-4d04-911c-710b7163c424",
  magnetShibuyaWithShanks = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/MagnetShibuyaWithShanks.jpg?alt=media&token=52b271d1-30be-489e-a1ae-9da947ed65af",
  meguroRiverFigLeafPose = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/MeguroRiverFigLeafPose.jpg?alt=media&token=6c1afb2e-2d71-4190-8f05-82f9e6e36d2c",
  meguroRiverPocketPose = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/MeguroRiverPocketPose.jpg?alt=media&token=373a7693-ae4d-4a0d-b609-5f61336e7335",
  meijiShrineWithBro = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/MeijiShrineWithBro.jpg?alt=media&token=35324995-b42a-4b13-8d31-bac0b0022138",
  meijiShrineWish = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/MeijiShrineWish.jpg?alt=media&token=8ee0c85e-e3a4-470e-8d80-68f4a4795e62",
  mishimaSkywalkPeripheral = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/SkywalkPeripheral.jpg?alt=media&token=2fb0246e-fce7-480c-8c94-eef969ce9644",
  naritaAirportWithBro = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/NaritaAirportWithBro.jpg?alt=media&token=422180f2-cd8f-410a-9d74-0a81d1a9949e",
  naritaExpressTicket = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/NaritaExpressTicket.jpg?alt=media&token=5b45d36d-5f87-495d-a819-e0fdf611d6d2",
  naritaExpressViewOutsideWindow = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/NaritaExpressViewOutsideWindow.jpg?alt=media&token=bc14d5d5-db6e-4265-92ba-0265e6259766",
  naritaExpressWithBro = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/NaritaExpressWithBro.jpg?alt=media&token=c8156c9c-e744-46d4-aa78-132c65314c77",
  planeToNaritaWithBro = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/PlaneToNaritaWithBro.jpg?alt=media&token=ca623d4e-e2b2-4c99-a651-9e27b369d0df",
  redTowerDay = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/RedTowerDay.jpg?alt=media&token=249a3251-8833-4c05-93cd-b597af7e1765",
  redTowerNight = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/RedTowerNight.jpg?alt=media&token=afc8b600-5f19-4ac8-a845-1a18f56ed8b3",
  redTowerPeacePose = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/RedTowerPeace.jpg?alt=media&token=0d882e10-c626-4ff1-a975-ec614c2493cd",
  shibuyaHachiko = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/ShibuyaHachiko.jpg?alt=media&token=516a2f9b-ffdf-4b9c-9a5f-8b98d0869035",
  shibuyaHachikoWithBro = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/ShibuyaHachikoWithBro.jpg?alt=media&token=e0c479a6-77d3-40e0-98b8-43d2dbed4e0f",
  shibuyaParcoMeasureHeight = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/ShibuyaParcoMeasureHeight.jpg?alt=media&token=d16d884e-20e1-4901-8277-b7926256fdef",
  shibuyaParcoWithMewtwo = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/ShibuyaParcoWithMewtwo.jpg?alt=media&token=e1244d18-98cf-41fb-b588-676fbc1e59a8",
  shibuyaSkyNightCityscape = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/ShibuyaSkyNightCityscape.jpg?alt=media&token=ce387be6-eb68-4274-8f33-9fb0360ed60c",
  shinjukuHotelWithBro = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/ShinjukuHotelWithBro.jpg?alt=media&token=c24087b3-576d-423e-b447-8d0b97346e63",
  shinkansenWithBro = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/ShinkansenWithBro.jpg?alt=media&token=b10918c4-cafd-42fc-b801-c4c1e1daba2b",
  shiseidoForestValleyWithFamily = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/ShiseidoForestValleyWithFamily.jpg?alt=media&token=cfd5b807-d910-4d87-abf1-546fc46eb00f",
  sourbombeWithFriends = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/SourbombeWithFriends.jpg?alt=media&token=bd09df90-0706-4390-ba65-a5504edbfd07",
  takeshitaWithBro = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/TakeshitaWithBro.jpg?alt=media&token=2925442a-8313-4efb-942d-9b66fb157f3d",
  tenYenPancake = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/10YenPancake.jpg?alt=media&token=f7df72f4-ee2e-47eb-bfdb-edd12394f792",
  tokyoSkytreeWithBro = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/SkytreeWithBro.jpg?alt=media&token=c76abd90-e8ac-4a15-a7fb-2df257c3d98a",
  vjwCustoms = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/VjwCustoms.png?alt=media&token=3d8e1e1b-42d1-42a1-af4f-c01d860e613f",
  vjwImmigration = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/VjwImmigration.png?alt=media&token=16c61190-7566-401c-ab83-cd8dbf20f310",
  vjwReview = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/VjwReview.png?alt=media&token=85304035-4c2a-4ec4-bcea-31371be52a4f",
  yoyogiParkTransparentToilet = "https://firebasestorage.googleapis.com/v0/b/marchtojapan.appspot.com/o/YoyogiParkTransparentToilet.jpg?alt=media&token=7179e2a7-204e-4ea4-bad4-ab064c474ea7",
}
